DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  urlString TEXT NOT NULL,
  timeLimit INTEGER NOT NULL,
  stat TEXT not NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE stats(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  urlString TEXT NOT NULL,
  timeLimit INTEGER NOT NULL,
  stat INTEGER not NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE fullData (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  urlString TEXT NOT NULL,
  timeLimit INTEGER NOT NULL,
  stat TEXT not NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);